# Site settings
title: The Queen's Court
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.queenscourt.org" # the base hostname & protocol for your site
filehost: "http://queenscourt.updog.co"
destination: _site

# Build settings
markdown: kramdown
exclude: ['Gemfile', 'Gemfile.lock', 'README.md']

# Collection. For redudancy and data gathering.
# All data going stored. i.e  "site.games[0].title".
collections:
  games:
    output: true
  misao:
    output: true
  reviews:
    output: true

# Default value for all page.
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

# Page generator
page_gen:
  - data: screenshots
    template: screenshots
    name: imageid
    dir: screenshots
    extension: html
